### ISSUE TITLE
extending the API

### ISSUE THREAD

**Issue by HomeACcessoryKid** [HomeACcessoryKid/ESP8266-HomeKit#14]
... understanding more it seems the problem does not exist ... see last answer

Currently the API works but is a bit limited.  
We can upload an initial value and a callback for a set of predefined cTypes.
All this is coded in the function `addCharacteristic`

However, there are cTypes that need more variables than that.

How do we feel we want additional variables to be conveyed to the more complex characteristics?

My best guess for now is to set up a few variables like item1 through item9 that if you set them before defining a characteristic they will set a particular variable of a particular characteristic.

Does anyone have a better idea??
PS, do not overcomplicate it please...

**Comment by AdySan** [comment]
Just to understand your question better, let me pull an example from [HAP-NodeJS](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js). You're looking for a way to define this structure in C, is that right?

```js
/**
 * Characteristic "Brightness"
 */

Characteristic.Brightness = function() {
  Characteristic.call(this, 'Brightness', '00000008-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.INT,
    unit: Characteristic.Units.PERCENTAGE,
    maxValue: 100,
    minValue: 0,
    minStep: 1,
    perms: [Characteristic.Perms.READ, Characteristic.Perms.WRITE, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
};

inherits(Characteristic.Brightness, Characteristic);

Characteristic.Brightness.UUID = '00000008-0000-1000-8000-0026BB765291';
```

**Comment by HomeACcessoryKid** [comment]
Actually when I opened this issue, I was not aware of how the HomeKit philosophy works. But actually the issue does not exist and the current approach is already OK.  
Basic idea is that each type of characteristic has its build in variables, predefined for this very characteristic. So they go statically inside the API and the outside user has not to worry about them.

I will close the issue...

**Comment by Maxmudjon** [comment]
addCharacteristic(chas,aid,++iid,APPLE,THERMOSTAT_C,"x1","x2","x3","x4",thermostat);
x1 - Current temperature
x2 - Target temperature
x3 - Current Heating/Cooling State
x4 - Target Heating/Cooling State
