### ISSUE TITLE
Add to ESP8285 taget support (Sonoff style of devices)

### ISSUE THREAD

**Issue by felixekman** [HomeACcessoryKid/ESP8266-HomeKit#15]
This would be perfect for the Sonoff type of line. But they use ESP8285 that's almost the same as the ESP8266 but with built-in 1MB flash.

Line of products example:
https://www.itead.cc/smart-home/sonoff-touch.html
https://www.itead.cc/smart-home/motor-reversing-wifi-wireless-switch.html

**Comment by AdySan** [comment]
Minor correction there, it's ESP82*8*5 not ESP82*6*5. 

Do you know if it is supported in the ESP8266_RTOS_SDK, or what changes need to be made in order to support it? I believe the only change is that the flash is wired to a different port.

**Comment by felixekman** [comment]
Yeah you're right, slip of the fingers ^^ 

I don't have a unit to try on actually. But I think they do a different flash layout, pinout should be the same I think.

**Comment by AdySan** [comment]
Looks like the only change required is to change SPI_MODE to DIO, and that can be selected while running `./gen_misc.sh`

**Comment by felixekman** [comment]
I'll purchase a few units and give it a try, but bodes well. Dream would be to have HomeKit and Alexa (wemos or hue emulation) working on the same device like one of these.

**Comment by AdySan** [comment]
The Alexa integration only exists as a Arduino library at the moment. If
someone could find a working example with the RTOS SDK, might be easy to
port. But I doubt that it'll work given the resource requirements of
HomeKit itself.

**Comment by felixekman** [comment]
Yeah I was looking into that as well, especially considering most of the units having only 1MB to work with as well. Though some of the Sonoff stuff like the S20 have an ESP8266 with the ability to replace the SPI flash for something bigger like a 4MB chip.

S20: https://www.itead.cc/smart-home/smart-socket.html

**Comment by malhal** [comment]
Hi any updates on wether this works on the Sonoff devices? Very interested to hear about it, thanks.

Thought I'd also share this video I found of how to upgrade the flash: [Youtube: Sonoff flash upgrade](https://youtu.be/8mz5sCAvDAY?t=4m30s). But it sounds like it isn't necessary for this project.

**Comment by malhal** [comment]
It's been a while just managed if anyone has managed to get this HomeKit capable firmware working on the cheap Sonoff devices? Given these are $4 and the official Bluetooth (not even any WiFi available yet) HomeKit plugs are $75 I thought there would be at least someone trying.

**Comment by HomeACcessoryKid** [comment]
https://github.com/RavenSystem/esp-homekit-devices/wiki
