### ISSUE TITLE
NOOS SDK

### ISSUE THREAD

**Issue by VasiliyLuch** [HomeACcessoryKid/ESP8266-HomeKit#16]
Thank you for your hard work.
I just setting my environment for esp dev. So I new in C.
Please tell me what  point of using RTOS?
Is it possible to use NONOS?
Thank you.

**Comment by AdyiPool** [comment]
Perhaps you can read [this](https://github.com/HomeACcessoryKid/Arduino-HomeKit/issues/1#issuecomment-269510447) thread first
