### ISSUE TITLE
Web server for config

### ISSUE THREAD

**Issue by malhal** [HomeACcessoryKid/ESP8266-HomeKit#17]
Either rest API or website for config would be good, like some of the other firmwares have.

**Comment by HomeACcessoryKid** [comment]
Hi malhal,

Could you elaborate on what type of configuration you would like to do?

In one hand I won't stop anyone adding such configuration but I have the impression that this is not what Apple has in mind with the HomeKit protocol.  
The idea seems to be that the binding is very secure and that no further config is needed nor allowed (other than what you might achieve by adding a service that could set what you want)  
Setting the Wifi is another thing, but in normal circumstances is a one time action. It appears that Apple has some bootstrap concept for wifi. If anyone has details on that, that would be interesting...

If some http based configuration would be needed, the parser is already there.
I could imagine a service that enables this api during one minute and disables automatically.
Even then, it would be a bit of a side door in a strong concept...  

Finally, any normal accessory would have a physical button to return to factory reset. Such a button can also be used to enter a configuration mode after a shorter press.

My 2 cents,
HacK

**Comment by malhal** [comment]
Sure, I'd like to set the Wi-Fi settings and IP configuration. I might change my network or lend the device to a friend to try on their network. Also I'd eventually like to be able to set the switch state on boot ([GPIO Boot States]((https://youtu.be/Kp4KJVbOWd0?t=4m0s))), and in my particular case rather than defaulting the light on or off I'd like it to default to the opposite of the current state, so that I can use a push-to-break wall switch thus providing traditional manual control of the light. I saw this initial state configuration in an ESPEasy configuration [video]((https://youtu.be/Kp4KJVbOWd0?t=4m0s)) but it does not include the option to reverse state.

I'd be happy with the upload of a configuration file than say various REST endpoints or a bulky website. So the same as how Apple's Airports work - they accept configuration then reboot.

If it's used in the home on a secured Wi-Fi network then any further security is unnecessary, but I suppose a password hash could be included in the configuration.

As you say a reset button could return the device to a default state, for example it becomes a Wi-Fi hotspot, the same way the Airport Express works. Then it can be connected to and a configuration uploaded to connect it to the home's Wi-Fi network. It appears that bluetooth has been added to a new version of this chip, the ESP32, so it's possible that configuration via bluetooth could be done when the device has lost Wi-Fi for some reason but the user does not wish to reset it. The HomeKit protocol can run over bluetooth too.

**Comment by AdySan** [comment]
@HomeACcessoryKid Regarding this,

>  It appears that Apple has some bootstrap concept for wifi. If anyone has details on that, that would be interesting...

I believe the keyword you're looking for Wireless Accessory Configuration (WAC). It's a very clever way to securely provision wifi credentials to the accessory, and makes for a rather delightful setup experience. Unfortunately, there's hardly any documentation about it in the public domain. [This](http://www.ti.com/lit/wp/swry011/swry011.pdf) is level of detail I could find online:

> The Wireless Accessory Configuration (WAC) feature is an Apple MFi licensed technology designed for MFi
accessories that connect to iPod, iPhone and iPad. MFi accessories that support WAC can be easily configured
by an iPod, iPhone and iPad, without requiring the user to type in the network name and password. Detailed
information about the WAC feature is available to Apple MFi Development and Manufacturing licensees.

**Comment by lou-lan** [comment]
Smarttconfig automatically configures WiFi and passwords to automatically connect to your home wireless network
