### ISSUE TITLE
add ESP8266-HomeKit to sonoff touch?

### ISSUE THREAD

**Issue by manuelgallego94** [HomeACcessoryKid/ESP8266-HomeKit#24]
hello !
someone have included this Github to iTead Sonoff touch? 
thank you very much.

**Comment by HomeACcessoryKid** [comment]
[This website](http://xbmcnut.blogspot.nl/2017/02/how-to-flash-espeasy-onto-sonoff-touch.html) suggests  it is not ESP8266 based.

I have no such device to experiment with, so tinkering and experimenting is required... and the outcome uncertain.

**Comment by legotheboss** [comment]
ESP8285 is the same as an ESP8266, but with an embedded 1MB of flash...

**Comment by ageorgios** [comment]
also for the iTead Sonoff Basic would be a great implementation!

**Comment by AdySan** [comment]
Looks like @Andreaqc is working on this https://github.com/Andreaqc/Sonoff-ESP8266-HomeKit
