### ISSUE TITLE
Village at sha2017.org

### ISSUE THREAD

**Issue by M10tech** [HomeACcessoryKid/ESP8266-HomeKit#25]
A homekit village has been started by me.

I will attend at SHA2017, the famous hacker festival in the Netherlands held every 4 years.

I hope we can meet with likeminded HomeKit hackers and make the Arduino library or assembly crypto. And make those hardware items that have shown up the other day...

If you are interested, please leave a message or contact me at home-accessory-at-xs4all.nl

**Comment by conkerkh** [comment]
As per license agreement (Apple homekit license for makers) is it legal to publish open source code? I was wondering about doing the same but in more general form using plain C. I think it should be ok to publish precompiled binaries but I'm not sure about the code itself.

**Comment by danielcompton** [comment]
I'm an MFI licensee, I've sent a message through the MFI console and will update when I hear back. I had the same questions too.

**Comment by HomeACcessoryKid** [comment]
Personally I am not bound to any apple developer conditions (never accepted those). The info is out in the open as explained in the Readme in the bottom. On the SHA2017 Homekit Village page there is a link to the specs without jumping through Apples hoop.
Of course you can always get a pseudonym and contribute like that.
