### ISSUE TITLE
implicit declaration of function 'wc_HKDF' (hkc.c)

### ISSUE THREAD

**Issue by kostasoft** [HomeACcessoryKid/ESP8266-HomeKit#27]
Hello!
After replacing the file hkc.c with a new one, this error occurs when compiling. The old file is compiled normally

**Comment by lindien954** [comment]
Hi,
Have you do this after replacing hkc.c ?
ESP8266_RTOS_SDK$ cd ESP8266-HomeKit
ESP8266-HomeKit$ ./deploy.sh

**Comment by kostasoft** [comment]
Oh sure. So I compile

**Comment by kostasoft** [comment]
![compile](https://user-images.githubusercontent.com/7292854/29358280-24cddcb0-8283-11e7-9918-26401d4f4ec1.PNG)

**Comment by kostasoft** [comment]
I added:
#include <wolfssl / wolfcrypt / hmac.h>
And everything became normal
