### ISSUE TITLE
Use homekit on Arduino

### ISSUE THREAD

**Issue by ToXiiK** [HomeACcessoryKid/ESP8266-HomeKit#34]
Hello
I wish I could use homekit on the arduino IDE, does anyone know how?

Thanking you in advance

cordially

**Comment by HomeACcessoryKid** [comment]
please refer to the other repository dedicated to that

**Comment by nbJosh** [comment]
What other repository?  URL please

**Comment by HomeACcessoryKid** [comment]
https://github.com/HomeACcessoryKid/Arduino-HomeKit
