### ISSUE TITLE
video instruction

### ISSUE THREAD

**Issue by Kristian8606** [HomeACcessoryKid/ESP8266-HomeKit#43]
can someone make a video with instructions on how to make a homekit accessory from esp8266

**Comment by AngryGinger** [comment]
anybody ? :smile:

**Comment by CustomMa-de** [comment]
Yes, I would like that, too...
It always helps me to see others do something that I want to learn...

**Comment by Kristian8606** [comment]
Come people help me someone.
please give me video instructions.

**Comment by alc7328** [comment]
Upvote this. I'd love to use this but it is a little advanced this way for me.
