### ISSUE TITLE
Toogle Switch

### ISSUE THREAD

**Issue by AngryGinger** [HomeACcessoryKid/ESP8266-HomeKit#44]
Hey !
I found a firmware pre-compile on the internet ([here](https://www.reddit.com/r/HomeKit/comments/7pxcsv/custom_firmware_now_allows_the_sonoff_basic_to_be/)) and it runs great but I would like to make a change so that the switch is recognized as a tootgle (dry contact).

Can anyone help me ?

**Comment by maccoylton** [comment]
UPDATE 17 Dec 2017

Please read the message in issue 41 about the switchover to Maxim Kulkin code base.

**Comment by AngryGinger** [comment]
I did not find which modification I have to bring to feign a dry contact recognized by HomeKit

Can you help me ?

**Comment by maccoylton** [comment]
look here for source and examples on using the new library on Sonoff devices

https://github.com/RavenSystem/esp-homekit-devices
