### ISSUE TITLE
How to wipe SRP Key and Wi-Fi credentials

### ISSUE THREAD

**Issue by legotheboss** [HomeACcessoryKid/ESP8266-HomeKit#8]
I paired and unpaired my ESP8266 with HomeKit. Now when I try to repair, they fail. I have traced this to the SRP Key and stored Wi-Fi credentials. How can I clear this part of the flash on the ESP8266?

This is the output in my console:
````
pairing 0, heap 19848, system time=7652
pairing 0, heap 19808, system time=10652
pairing 0, heap 19808, system time=13652
chas: 1.9=valF -> bool
pairing 0, heap 19808, system time=16652
pairing 0, heap 19808, system time=19652
pairing 0, heap 19808, system time=22652
pairing 0, heap 19808, system time=25652
pairing 0, heap 19808, system time=28652
chas: 1.9=valT -> bool
pairing 0, heap 19808, system time=31652
````

**Comment by AdySan** [comment]
Have you tried to erase all of flash?
'esptool.py --baud 230400 -p /dev/tty.SLAB_USBtoUART erase_flash'

I did this but now the ESP keeps rebooting after flashing the bin files, looks like this erased more than what needed to be erased. Do you flash anything other than 'eagle.flash.bin' and 'eagle.irom0text.bin'?

**Comment by legotheboss** [comment]
@AdySan I completely erased my ESP8266 as well and running into same problem

**Comment by AdySan** [comment]
For now I'm just using another board.

**Comment by HomeACcessoryKid** [comment]
It is clear that the pending thing is to write some instructions... :-)

To start, unpairing should have mutilated the signature in sector 13 with the client key (pairdel function).
This signature shows if the sector is valid or not. If not, sector 13 is erased.
You can change the signature  in the source code if you want to provoke an erase.
Next, if no client key is found, then pairing is 1 and you should be able to pair.
The initial debugging info shows if this is the case.

hkc by HomeACcessoryKid! Compiled Dec 24 2016@17:06:52 Heap: 47864
EspMsgMutex created
486f6d654143636573736f72794b696400    `the signature is valid`
\<snip my key\>    
key loaded:  0    `it found a key`
pairing: 0    `so we are not pairing`
007fffffffffffffffffffff39\<snip rest of client key>\

ifdef FACTORY, you can send a http request to the device and it will kill the signature.
wget http://192.168.your.ip:57005/factory  
(note I will switch to port 661 soon if you read this later)
Hope this helps

**Comment by HomeACcessoryKid** [comment]
@AdySan you should try to flash this:  
`../esptool/esptool.py write_flash 0x3fe000 bin/blank.bin 0x3fc000 bin/esp_init_data_default.bin`

These two files come with the ESP_RTOS_SDK  
[other addresses](https://nodemcu.readthedocs.io/en/master/en/flash/#sdk-init-data) if you have other flash size...

**Comment by legotheboss** [comment]
@HomeACcessoryKid How can one change the source code to clear sector 13?

**Comment by HomeACcessoryKid** [comment]
in the function crypto_init change the string signature[] to something else.
